# config/packages/vich_uploader.yaml
vich_uploader:
    db_driver: orm

    mappings:
        Datas:
            uri_prefix:         /Datas
            upload_destination: '%kernel.project_dir%/public/Datas'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
